{% set name = "camply" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/camply-{{ version }}.tar.gz
  sha256: 97ac130d67ac2e7b1212697615bde2773e7cc43cb27970b6e346e882b3df54f6

build:
  number: 0
  noarch: python
  entry_points:
    - camply = camply.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
  run:
    - click
    - pandas
    - pydantic
    - python >=3.6
    - python-dotenv
    - pytz
    - pyyaml
    - requests
    - rich
    - tenacity

test:
  imports:
    - camply
    - camply.config
    - camply.notifications
    - camply.providers
    - camply.providers.xanterra
    - camply.providers.recreation_dot_gov
    - camply.search
    - camply.utils
  commands:
    - pip check
    - camply --help
  requires:
    - pip

about:
  home: https://github.com/juftin/camply
  summary: camply, the campsite finder
  license: MIT
  license_file: LICENSE
  description: |
    Finding reservations at sold out campgrounds can be tough. That's where
     camply comes in. It searches the APIs of booking services like
     https://recreation.gov (which indexes thousands of campgrounds across the
     USA) to continuously check for cancellations and availabilities to pop up.
     Once a campsite becomes available, camply sends you a notification to book
     your spot!

extra:
  recipe-maintainers:
    - thewchan
