{% set name = "camply" %}
{% set version = "0.32.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/camply-{{ version }}.tar.gz
  sha256: d50d4211171666bde17d960e4b17b8012dcc4693e45093b41d2e27c2e4abe877

build:
  number: 0
  noarch: python
  entry_points:
    - camply = camply.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8,<4
  run:
    - python >=3.8,<4
    - click ~=8.1.3
    - fake-useragent ~=1.4.0
    - pandas >=2,<3
    - pydantic ~=1.10.13
    - python-dotenv ~=1.0.0
    - pytz ~=2023.2
    - pyyaml ~=6.0
    - ratelimit ~=2.2.1
    - requests ~=2.31.0
    - rich ~=13.3.2
    - rich-click ~=1.6.1
    - tenacity ~=8.2.2

test:
# Test suite kinda wonky removed for now
  imports:
    - camply
  commands:
    - pip check
    - camply --help
  requires:
    - pip

about:
  home: https://github.com/juftin/camply
  summary: camply, the campsite finder
  license: MIT
  license_file: LICENSE
  description: |
    Finding reservations at sold out campgrounds can be tough. That's where
     camply comes in. It searches the APIs of booking services like
     https://recreation.gov (which indexes thousands of campgrounds across the
     USA) to continuously check for cancellations and availabilities to pop up.
     Once a campsite becomes available, camply sends you a notification to book
     your spot!

extra:
  recipe-maintainers:
    - juftin
    - thewchan
