{% set name = "camply" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/camply-{{ version }}.tar.gz
  sha256: e29c3ff7674f3538b8097cf27aab24eb5ad0c382531d2016632704546c668277

build:
  number: 0
  noarch: python
  entry_points:
    - camply = camply.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.1,<4.0
  run:
    - click >=8.0.1
    - fake-useragent >=1.1.1,<2.0.0
    - pandas <1.4,>=1.3
    - pydantic >=1.2,<2.0
    - python >=3.7.1,<4.0
    - python-dotenv >=0.10.4
    - pytz >=2019.1
    - pyyaml >=5.1,<7.0
    - ratelimit >=2.2.1,<3.0.0
    - requests >=2.26.0
    - rich >=10.0.0
    - rich-click >=1.6.1,<2.0.0
    - tenacity >=5.1.0

test:
  imports:
    - camply
  commands:
    - pip check
    - camply --help
  requires:
    - pip

about:
  home: https://github.com/juftin/camply
  summary: camply, the campsite finder
  license: MIT
  license_file: LICENSE
  description: |
    Finding reservations at sold out campgrounds can be tough. That's where
     camply comes in. It searches the APIs of booking services like
     https://recreation.gov (which indexes thousands of campgrounds across the
     USA) to continuously check for cancellations and availabilities to pop up.
     Once a campsite becomes available, camply sends you a notification to book
     your spot!

extra:
  recipe-maintainers:
    - thewchan
