{% set name = "camply" %}
{% set version = "0.32.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/camply-{{ version }}.tar.gz
  sha256: 126e834a3d3ce800376c2607edf26ba718b90c1c8e6c7e48c380264a6b9803ff

build:
  number: 0
  noarch: python
  entry_points:
    - camply = camply.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - click >=8.1.3,<8.2.dev0
    - fake-useragent >=1.4.0,<1.5.dev0
    - pandas >=2,<3
    - pydantic >=1.10.13,<1.11.dev0
    - python-dotenv >=1.0.0,<1.1.dev0
    - pytz >=2023.2,<2024.dev0
    - pyyaml >=6.0,<7.dev0
    - ratelimit >=2.2.1,<2.3.dev0
    - requests >=2.31.0,<2.32.dev0
    - rich-click >=1.6.1,<1.7.dev0
    - rich >=13.3.2,<13.4.dev0
    - tenacity >=8.2.2,<8.3.dev0
    - python-dateutil

    # Needed but not listed
    - importlib_resources

test:
  imports:
    - camply
  commands:
    - pip check
    - camply --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/juftin/camply
  summary: camply, the campsite finder
  license: MIT
  license_file: LICENSE
  description: |
    Finding reservations at sold out campgrounds can be tough. That's where
     camply comes in. It searches the APIs of booking services like
     https://recreation.gov (which indexes thousands of campgrounds across the
     USA) to continuously check for cancellations and availabilities to pop up.
     Once a campsite becomes available, camply sends you a notification to book
     your spot!

extra:
  recipe-maintainers:
    - juftin
    - thewchan
