schema_version: 1

context:
  name: camply
  version: 0.33.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/camply-${{ version }}.tar.gz
  sha256: 4b6dbb4ca118ac6fa23274dd2abf386489d7b381498c1d15b9634ae214c95491

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - camply = camply.cli:cli

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - click ~=8.1.3
    - fake-useragent ~=1.4.0
    - pandas >=2,<3
    - pydantic ~=1.10.22
    - python-dotenv ~=1.0.0
    - pytz ~=2023.2
    - pyyaml ~=6.0
    - ratelimit ~=2.2.1
    - requests ~=2.31.0
    - rich ~=13.3.2
    - rich-click ~=1.6.1
    - tenacity ~=8.2.2

tests:
  - python:
      imports:
        - camply
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - camply --help

about:
  summary: camply, the campsite finder
  license: MIT
  license_file: LICENSE
  description: |
    Finding reservations at sold out campgrounds can be tough. That's where
    camply comes in. It searches the APIs of booking services like
    https://recreation.gov (which indexes thousands of campgrounds across the
    USA) to continuously check for cancellations and availabilities to pop up.
    Once a campsite becomes available, camply sends you a notification to book
    your spot!


  homepage: https://github.com/juftin/camply

extra:
  recipe-maintainers:
    - juftin
    - thewchan
